services:   # services we want to include
  # 1. service
  pgdatabase:
    image: postgres:13
    # environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # volumes to mount
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    # port mapping
    ports:
      - "5433:5432"
    networks:
      - airflow

  # 2. service
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - airflow

# network
networks:
  airflow:
    name: ${NETWORK_NAME}
    external: true
